#!/usr/bin/python

import numpy as np
import sys, os
if __name__ == "__main__":
	data = np.loadtxt(sys.stdin, delimiter=',' ,dtype=np.float)
	np.savetxt("_feature.csv", data, delimiter="," , fmt='%.1f')
	print "feature inserted : " + str(len(data)) + " rows"
	os.system( "head -n 1 _feature.csv > _test.csv")

