#!/usr/bin/python
import pandas
import sys

def runPandas(func_name , args):
	#print str(args), args[0]
	#print str(args[2:])

	df = pandas.read_csv(sys.stdin, header=None)
	col_name=[]
	for i in range(1, int(df.shape[1]) + 1):
		col_name.append('col' + str(i))
	df.columns = col_name
	m = getattr(df, func_name, None)
	if callable(m):
		arg = [float(i) for i in args]
        	res = m(*arg)
   	else:
		res = "Unknown function name"
        print res
	

if __name__ == "__main__":
	if len(sys.argv) > 1:
		func_name = sys.argv[1]
		runPandas(func_name, sys.argv[2:])
	else:
		print "pandas <func name>"
